# Generated by Django 4.0.1 on 2022-01-07 16:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mamono', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusmodels',
            name='picture',
            field=models.ImageField(default='defo', upload_to='char_image/'),
        ),
        migrations.AlterField(
            model_name='statusmodels',
            name='ID',
            field=models.UUIDField(default=uuid.UUID('8550f9a5-6392-4038-ada1-a0af886ac09c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
