# Generated by Django 4.0.1 on 2022-01-07 16:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mamono', '0002_statusmodels_picture_alter_statusmodels_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusmodels',
            name='ID',
            field=models.UUIDField(default=uuid.UUID('cd0341bd-cee3-412a-a29f-55f2cf951197'), editable=False, primary_key=True, serialize=False),
        ),
    ]
