# Generated by Django 4.0.1 on 2022-01-08 10:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkillModels',
            fields=[
                ('skill_name', models.CharField(max_length=20, unique=True)),
                ('skill_attack', models.IntegerField()),
                ('id', models.UUIDField(default=uuid.UUID('4db43783-641a-4a7a-b422-e60528b0c4e3'), primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='StatusModels',
            fields=[
                ('name', models.CharField(max_length=20, unique=True)),
                ('picture', models.ImageField(default='defo', upload_to='char_image/')),
                ('HP', models.IntegerField()),
                ('MP', models.IntegerField()),
                ('id', models.UUIDField(default=uuid.UUID('341e0c6a-1de6-4859-ab18-2428d059c45e'), editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='RaceModels',
            fields=[
                ('race_name', models.CharField(max_length=20, unique=True)),
                ('id', models.UUIDField(default=uuid.UUID('affca704-b38d-4583-a605-2056637d9d6d'), primary_key=True, serialize=False)),
                ('race_skill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.skillmodels')),
            ],
        ),
        migrations.CreateModel(
            name='YushaModels',
            fields=[
                ('statusmodels_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='character.statusmodels')),
                ('lv', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('race', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.racemodels')),
                ('skill1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.skillmodels')),
            ],
            bases=('character.statusmodels',),
        ),
        migrations.CreateModel(
            name='MonsterModels',
            fields=[
                ('statusmodels_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='character.statusmodels')),
                ('skill1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.skillmodels')),
            ],
            bases=('character.statusmodels',),
        ),
    ]
