# Generated by Django 4.0.1 on 2022-01-08 10:26

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racemodels',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b06df3b3-97f3-49be-8c5f-77403a4921f0'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='skillmodels',
            name='id',
            field=models.UUIDField(default=uuid.UUID('75159d97-8c03-42e2-8cbb-fe23ef52c5e9'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='skillmodels',
            name='skill_attack',
            field=models.PositiveBigIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='statusmodels',
            name='id',
            field=models.UUIDField(default=uuid.UUID('81baed8b-0c95-4d72-aef8-837949cba945'), editable=False, primary_key=True, serialize=False),
        ),
    ]
