# Generated by Django 4.0.1 on 2022-01-08 10:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_alter_racemodels_id_alter_skillmodels_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racemodels',
            name='id',
            field=models.UUIDField(default=uuid.UUID('38592579-619f-4a2f-a248-399235a5c326'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='skillmodels',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e591f21b-541f-49ed-a22f-7394da2b2306'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='statusmodels',
            name='id',
            field=models.UUIDField(default=uuid.UUID('82806c0c-4d63-4140-85b7-98744456e688'), editable=False, primary_key=True, serialize=False),
        ),
    ]
