# Generated by Django 4.0.1 on 2022-01-08 10:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0003_alter_racemodels_id_alter_skillmodels_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racemodels',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='skillmodels',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='statusmodels',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4c824a1c-911a-4e46-b667-48e97c8d226b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
