# Generated by Django 4.0.1 on 2022-01-08 14:27

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0004_alter_racemodels_id_alter_skillmodels_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillmodels',
            name='skill_attack',
            field=models.PositiveBigIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='statusmodels',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4a12663b-2a25-4575-b76a-0afcd84d0896'), editable=False, primary_key=True, serialize=False),
        ),
    ]
