# Generated by Django 4.0.1 on 2022-01-08 14:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0005_alter_skillmodels_skill_attack_alter_statusmodels_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusmodels',
            name='id',
            field=models.UUIDField(default=uuid.UUID('63744ffa-5ce5-4f40-becb-35e414b6556f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
