# Generated by Django 4.0.1 on 2022-01-08 15:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0007_alter_statusmodels_hp_alter_statusmodels_mp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusmodels',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f967be34-706a-43d2-85b4-e795e66bc900'), editable=False, primary_key=True, serialize=False),
        ),
    ]
