# Generated by Django 3.2.9 on 2022-01-17 06:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0008_alter_statusmodels_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusmodels',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4e460d8b-a5e8-4946-9190-b807ee8a98c1'), editable=False, primary_key=True, serialize=False),
        ),
    ]
